version: "3"

services:
  tooljet:
    build:
      context: ./
      dockerfile: ./docker/production.Dockerfile
    image: tooljet-ce-cn:latest
    platform: linux/x86_64
    volumes:
      - ./plugins:/app/plugins
      - ./frontend:/app/frontend:delegated
      - ./server:/app/server:delegated

      - /app/frontend/node_modules/
      - /app/server/node_modules/

      - ./.env:/app/.env
      - ./.env.test:/app/.env.test
      - ./.env.production:/app/.env.production
    extra_hosts:
      - "host.docker.internal:host-gateway"
