version: "3"

services:
  plugins:
    image: tooljet:production
    platform: linux/x86_64
    volumes:
      - ./plugins:/app/plugins
    command: npm run --prefix plugins start

#  client:
#    image: tooljet:production
#    platform: linux/x86_64
#    volumes:
#      - ./frontend:/app/frontend:delegated
#      - ./plugins:/app/plugins
#      - /app/frontend/node_modules/
#    ports:
#      - 8082:8082
#    environment:
#      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
#      - SERVE_CLIENT=false
#    command: npm run --prefix frontend start

  server:
    image: tooljet:production
    platform: linux/x86_64
    volumes:
      - ./server:/app/server:delegated
      - ./plugins:/app/plugins
      - /app/server/node_modules/
      - ./.env:/app/.env
      - ./.env.test:/app/.env.test
    ports:
      - 3000:3000
    environment:
      - SERVE_CLIENT=false
      - FORCE_COLOR=1
    command: npm run --prefix server start:prod
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/data/postgres
    environment:
      - POSTGRES_PASSWORD=postgres

#volumes:v
#  postgres:
