version: '3'

services:
  server:
    tty: true
    stdin_open: true
    image: tooljet/tooljet-ce-cn:latest
    restart: always
    env_file: .env
    ports:
      - 8082:8082
    environment:
      SERVE_CLIENT: "true"
      PORT: "8082"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: npm run start:prod
